#!/bin/bash

# Milk Station Node - Wokwi Simulation Script
# Simulates a complete milking session with RFID cow identification

echo "╔══════════════════════════════════════════════════════════╗"
echo "║     MILK STATION NODE - WOKWI SIMULATION                ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""
echo "📋 SIMULATION OVERVIEW:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "This simulation demonstrates a fixed milking station with:"
echo "  • RFID cow identification"
echo "  • Milk flow measurement"
echo "  • Milk quality monitoring (temperature, pH, conductivity)"
echo "  • 20x4 LCD display for farmer"
echo "  • LoRa data transmission"
echo "  • WiFi connectivity to Device Manager"
echo ""
echo "🎛️  WOKWI COMPONENTS:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  • ESP32 DevKit C V4 (main controller)"
echo "  • DS18B20 Temperature Sensor (milk temperature)"
echo "  • 20x4 LCD Display with I2C (farmer interface)"
echo "  • 3 LEDs (Green=OK, Red=Alert, Blue=Boot)"
echo "  • 2 Potentiometers (pH and conductivity simulation)"
echo "  • 1 Pushbutton (milk flow pulse simulation)"
echo ""
echo "📍 PIN CONNECTIONS:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Temperature Sensor:"
echo "  DS18B20 → GPIO 4 (with 4.7kΩ pull-up to 3.3V)"
echo ""
echo "LCD Display (I2C):"
echo "  SDA → GPIO 21"
echo "  SCL → GPIO 22"
echo "  Address: 0x27"
echo ""
echo "Status LEDs:"
echo "  Green (Status OK) → GPIO 2 (220Ω resistor)"
echo "  Red (Alert)       → GPIO 27 (220Ω resistor)"
echo "  Blue (Boot)       → GPIO 14 (220Ω resistor)"
echo ""
echo "Milk Sensors:"
echo "  pH Potentiometer        → GPIO 36 (ADC)"
echo "  Conductivity Pot        → GPIO 39 (ADC)"
echo "  Flow Pulse Button       → GPIO 25"
echo ""
echo "LoRa Module (SPI):"
echo "  CS   → GPIO 18"
echo "  SCK  → GPIO 5"
echo "  MOSI → GPIO 23"
echo "  MISO → GPIO 19"
echo "  RST  → GPIO 14"
echo "  DIO0 → GPIO 26"
echo ""
echo "🎯 SIMULATION SCENARIOS:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "SCENARIO 1: Normal Milking Session"
echo "────────────────────────────────────"
echo "  1. System boots, LCD shows 'Milk Station Ready'"
echo "  2. Green LED ON (system healthy)"
echo "  3. Waiting for RFID cow tag scan"
echo "  4. [Simulated] Cow COW-001 detected"
echo "  5. LCD shows: 'Welcome COW-001'"
echo "  6. Click Flow Button to simulate milk flow"
echo "  7. LCD updates with volume, temperature, pH"
echo "  8. Milk temperature: 4.5°C (adjust DS18B20)"
echo "  9. pH: ~6.6 (adjust pH potentiometer)"
echo " 10. Conductivity: normal (adjust conductivity pot)"
echo " 11. Session ends, data transmitted via LoRa/WiFi"
echo ""
echo "SCENARIO 2: Milk Quality Alert"
echo "────────────────────────────────────"
echo "  1. Adjust pH potentiometer to extreme value"
echo "  2. System detects pH < 6.4 or > 6.8"
echo "  3. Red LED blinks (quality alert)"
echo "  4. LCD shows: 'ALERT: Abnormal pH'"
echo "  5. Farmer notification sent"
echo ""
echo "SCENARIO 3: Mastitis Detection"
echo "────────────────────────────────────"
echo "  1. Adjust conductivity potentiometer HIGH"
echo "  2. System detects conductivity > 5.5 mS/cm"
echo "  3. Red LED ON (health alert)"
echo "  4. LCD shows: 'WARNING: High Conductivity'"
echo "  5. Recommendation: 'Check udder health'"
echo ""
echo "🎮 INTERACTIVE CONTROLS:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  DS18B20 Temperature:"
echo "    • Click on sensor to adjust milk temperature"
echo "    • Normal range: 2-6°C"
echo "    • Too high → spoilage risk"
echo ""
echo "  pH Potentiometer:"
echo "    • Rotate to simulate pH changes"
echo "    • Normal: 6.4-6.8 (mid position)"
echo "    • Low pH → acidic milk (bad)"
echo "    • High pH → possible contamination"
echo ""
echo "  Conductivity Potentiometer:"
echo "    • Rotate to simulate conductivity"
echo "    • Normal: ~4.5 mS/cm (low-mid position)"
echo "    • High: >5.5 mS/cm → mastitis indicator"
echo ""
echo "  Flow Pulse Button:"
echo "    • Click repeatedly to simulate milk flow"
echo "    • Each click = milk pulse"
echo "    • Volume calculated from pulse count"
echo ""
echo "📊 LCD DISPLAY OUTPUT:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Line 1: Cow ID or status message"
echo "Line 2: Milk volume (liters)"
echo "Line 3: Temperature and pH"
echo "Line 4: Status or alerts"
echo ""
echo "Example Normal Display:"
echo "┌────────────────────┐"
echo "│ COW-001  Milking   │"
echo "│ Volume: 12.5 L     │"
echo "│ Temp:4.5C pH:6.6   │"
echo "│ Status: Good       │"
echo "└────────────────────┘"
echo ""
echo "Example Alert Display:"
echo "┌────────────────────┐"
echo "│ COW-001  ALERT!    │"
echo "│ Volume: 8.2 L      │"
echo "│ Temp:7.2C pH:7.1   │"
echo "│ High Temp & pH!    │"
echo "└────────────────────┘"
echo ""
echo "💡 EXPECTED SERIAL OUTPUT:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  • System initialization messages"
echo "  • LCD display updates"
echo "  • Sensor readings (temp, pH, conductivity)"
echo "  • Milk flow rate and volume"
echo "  • RFID scan status"
echo "  • LoRa transmission confirmations"
echo "  • Quality alerts and warnings"
echo ""
echo "🚀 HOW TO RUN SIMULATION:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Method 1: VS Code Wokwi Extension"
echo "  1. Install 'Wokwi Simulator' extension in VS Code"
echo "  2. Open milk-station-node folder"
echo "  3. Press F1 → 'Wokwi: Start Simulator'"
echo "  4. Interact with components in Wokwi window"
echo ""
echo "Method 2: Wokwi CLI"
echo "  1. Build firmware: pio run"
echo "  2. Start Wokwi: wokwi-cli --web"
echo "  3. Open browser to displayed URL"
echo ""
echo "Method 3: Hardware Upload"
echo "  1. Connect ESP32 via USB"
echo "  2. Upload: pio run --target upload"
echo "  3. Monitor: pio device monitor"
echo ""
echo "📝 TESTING CHECKLIST:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ☐ Green LED lights on boot"
echo "  ☐ LCD displays 'Milk Station Ready'"
echo "  ☐ Temperature reading appears (4.5°C default)"
echo "  ☐ pH reading displays (adjust potentiometer)"
echo "  ☐ Conductivity reading shows (adjust potentiometer)"
echo "  ☐ Flow button increments milk volume"
echo "  ☐ Red LED alerts on quality issues"
echo "  ☐ LCD updates every 2 seconds"
echo "  ☐ Serial output shows all sensor data"
echo "  ☐ LoRa transmission attempts visible"
echo ""
echo "🔧 TROUBLESHOOTING:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Problem: LCD shows nothing"
echo "  → Check I2C address (0x27 or 0x3F)"
echo "  → Verify SDA/SCL connections (GPIO 21/22)"
echo ""
echo "Problem: Temperature always 0°C or 85°C"
echo "  → Check DS18B20 connections"
echo "  → Verify 4.7kΩ pull-up resistor"
echo ""
echo "Problem: LEDs not responding"
echo "  → Check GPIO pin numbers in config.h"
echo "  → Verify 220Ω resistors in series"
echo ""
echo "Problem: No LoRa transmission"
echo "  → Check LoRa module SPI connections"
echo "  → Verify frequency (915 MHz)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Ready to simulate! Build and start Wokwi simulator now."
echo ""
echo "Build command: pio run"
echo "Wokwi start:   Press F1 → 'Wokwi: Start Simulator'"
echo ""
